apiVersion: v1
kind: Pod

metadata:
  name: result-pod
  labels:
    app: result

spec:
    containers:
    - name: result-container
      image: dockersamples/examplevotingapp_result
      ports:
      - containerPort: 80