apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result
spec:
  replicas: 3
  selector:
    matchLabels:
      app: result
  template:
    metadata:
      name: result-pod
      labels:
        app: result

    spec:
      containers:
        - name: result-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80