apiVersion: v1
kind: Service

metadata:
  name: result-service
  labels:
    app: result

spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 31001
    selector:
        app: result
