apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: voting
spec:
  replicas: 3
  selector:
    matchLabels:
      app: voting
  template:
    metadata:
      name: voting-pod
      labels:
        app: voting

    spec:
      containers:
        - name: voting-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80