apiVersion: v1
kind: Pod

metadata:
  name: voting-pod
  labels:
    app: voting

spec:
    containers:
    - name: voting-container
      image: dockersamples/examplevotingapp_vote
      ports:
      - containerPort: 80