apiVersion: v1
kind: Service

metadata:
  name: voting-service
  labels:
    app: voting

spec:
    type: NodePort
    ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
    selector:
        app: voting
