apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      name: worker-pod
      labels:
        app: worker

    spec:
      containers:
        - name: worker-container
          image: dockersamples/examplevotingapp_worker
